### ISSUE TITLE
V560TNE v0.9.1-rc4 external audio jack mic not working

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1031]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc4

### Dasharo Tools Suite version

--

### Test case ID

AUD004.001, AUD006.001

### Brief summary

AUD004.001 is a fail, AUD006.001 internal mic is used

### How reproducible

100%

### How to reproduce

Do the AUD004 and 006 tests

### Expected behavior

AUD004: output of `amixer -c 0 contents | grep -A 2 'Front Headphone Jack'` should contain `: values=on`
AUD006: the external headset mic should be used

### Actual behavior

AUD004: The output is empty.  `amixer -c 0 contents | grep -A 2 'Jack'`  only contains HDMI audio devices
AUD006: The internal mic is used instead of the external. Can be verified by making noise near the headsets mic and internal mic and comparing the result. The external mic is not listed in GNOME settings' Sound tab.

### Solutions you've tried

Rebooting, reconnecting

**Comment by philipandag** [comment]
Still an issue on v0.9.1-rc5 on V540TND. The mic works if connected via a docking station.

**Comment by mkopec** [comment]
Looks like @marmarek submitted a fix to the upstream kernel: https://patchwork.kernel.org/project/alsa-devel/patch/20240903124939.6213-1-marmarek@invisiblethingslab.com/

However I'm not sure if the SMBIOS ID is correct for Nvidia models, it should be https://github.com/Dasharo/coreboot/blob/3d40d9aea271997e7c77982b9947d9ff1406b38c/src/mainboard/clevo/mtl-h/Kconfig#L72 

Sadly I missed the CC because I was on vacation at the time :melting_face:

**Comment by mkopec** [comment]
Fixed on Ubuntu 24.10 Beta, kernel 6.11.
