### ISSUE TITLE
Improve meta-dts test workflow

### ISSUE THREAD

**Issue by PLangowski** [Dasharo/dasharo-issues#1146]
### The problem you're addressing (if any)

The [test workflow](https://github.com/Dasharo/meta-dts/blob/379f816e541920a0d8e927da36b3962d8694c493/.github/workflows/test.yml) can be improved in several ways. The suggestions are listed [here](https://github.com/Dasharo/meta-dts/pull/193).

**Comment by DaniilKl** [comment]
I have another suggestion here.

Currently we are running test in the way, that if first set of tests fail (MSI tests as on the image below), other tests will not execute. For example, consider the image below. MSI tests are first in queue, but when it fails - other tests are not being executed, and entire workflow should be restarted.

![image](https://github.com/user-attachments/assets/78e43022-4df4-4c6a-a7b8-68db1c0b05fa)

Btw, @PLangowski, you should duplicate your suggestions in issues, because finding them in PR's is time-consuming.

**Comment by PLangowski** [comment]
My suggestions have been resolved in https://github.com/Dasharo/meta-dts/pull/200.
@DaniilKl Can you check if your is resolved [here](https://github.com/Dasharo/meta-dts/pull/200/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R34)? If so, this issue can be closed.

**Comment by DaniilKl** [comment]
> Can you check if your is resolved [here](https://github.com/Dasharo/meta-dts/pull/200/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R34)? If so, this issue can be closed.

:+1:
