### ISSUE TITLE
Selective Option ROM loading

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#117]
**The problem you're addressing (if any)**
Dasharo firmware loads EFI Option ROMs from the PCI devices to perform device specific initialization. However OptionROMs executed unconditionally may pose a security threat.

**Describe the solution you'd like**
Add a Dasharo setup option to control the OptionROm loading behavior:
- Enable all OptionROMs loading
- Disable all OptionROMs loading 
- Enable OptionROM loading only on GPUs

**Where is the value to a user, and who might that user be?**
Fine-grained control over the OptionROMs loading and better security. Qubes certification

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Firminator** [comment]
Would that affect PXE booting? In other  words would I not be able to PXE boot if I select "Disable all OptionROMs loading" or "Enable OptionROM loading only on GPUs"?

**Comment by mrothfuss** [comment]
it would be great if we could whitelist option roms.

ie: scan/save a rom checksum and only execute if it matches the trusted result.

**Comment by miczyg1** [comment]
> Would that affect PXE booting? In other words would I not be able to PXE boot if I select "Disable all OptionROMs loading" or "Enable OptionROM loading only on GPUs"?

Depends on the board, at least it won't affect boards with iPXE-supported Ethernet controllers. The MSI board for example uses the embedded driver inside the firmware image instead of Option ROMs (which were not really programmed in the first place).

**Comment by miczyg1** [comment]
> it would be great if we could whitelist option roms.
> 
> ie: scan/save a rom checksum and only execute if it matches the trusted result.

UEFI Secure Boot has such capability IIRC: https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot#signature-databases-and-keys
Adding given OptionROM hash to db should work

**Comment by zirblazer** [comment]
> * Enable all OptionROMs loading
> * Disable all OptionROMs loading
> * Enable OptionROM loading only on GPUs

I believe than this is rather suboptimal, and is not even useful for my particular usage. Figuring out if it can be fine tuned per PCIe Slot (Or PCIe Root Port, due to in-slot Bifurcation) basis is far more granular and useful.
The "enable Option ROM only on GPUs" means that if you have multiple GPUs, all their Option ROMs would be loaded, whereas for certain scenarios like PCI Passthrough of a GPU, you may want to make a card "primary" by NOT loading any other GPU Option ROMs. This may help with some cards that has quirks or other weird behavior (Like crashing when rebooting the VM) if its Option ROM is loaded on host boot. It would not be possible to do that with your arrangement.

Here is an example menu from a Supermicro X11DPi-N (My 2013 X10SAT for Haswell is very similar): https://www.thomas-krenn.com/en/wiki/Deactivate_OPROM_Reduce_boot_time
Some BIOSes (Not sure if Supermicro, but recall a Dual Socket ASUS from the same era) even allowed you to selectively choose per slot whenever to priorize either loading a Legacy BIOS Option ROMs, UEFI, only Legacy, only UEFI, or fully disable. Since this is pure UEFI and there is no CSM, it is pretty much an On/Off with no priority.

**Comment by miczyg1** [comment]
> I believe than this is rather suboptimal, and is not even useful for my particular usage.

This option was primarily focused on security, not compatibility or usability. Apologies we can't afford make multiple options with complex logic and menu layout at once...

**Comment by SergiiDmytruk** [comment]
https://github.com/Dasharo/DasharoModulePkg/pull/26
https://github.com/Dasharo/edk2/pull/72

**Comment by BeataZdunczyk** [comment]
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.
