### ISSUE TITLE
Dasharo setup password

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#120]
**The problem you're addressing (if any)**
Currently Dasharo setup menu is not password protected.

**Describe the solution you'd like**
Add Setup password implementation. There is a SMM-based implementation in edk2-platforms.

**Where is the value to a user, and who might that user be?**
For users wanting to protect the unauthorized access to options menu.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mkopec** [comment]
+1, it's too easy for an attacker to just disable Secure Boot at the moment. We could extend this to add a power-on password, too

**Comment by miczyg1** [comment]
@mkopec if you use a SATA disk today, you may already benefit from SATA password during power-on (but not resume)

**Comment by mkopec** [comment]
PR: https://github.com/Dasharo/DasharoModulePkg/pull/5

**Comment by mkopec** [comment]
Implemented in https://github.com/Dasharo/DasharoModulePkg/pull/5. The user management option appears on the front page of the setup menu:

![image](https://user-images.githubusercontent.com/3678707/198616168-f5b3bebb-e8b9-4131-a414-9ab341155a4b.png)

There, you can set an admin password:

![image](https://user-images.githubusercontent.com/3678707/198616439-0395f158-2422-4fa7-947a-de5e3e22696c.png)

And now, when entering the setup menu, you'll get a password prompt:

![image](https://user-images.githubusercontent.com/3678707/198616734-685b05fa-2ed5-4ed5-adef-83d6d78e56b7.png)

Additionally, since the password hash is stored in an EFI variable, it needs to be protected from overwriting from within the OS. So, a new option `Enable SMM BIOS write protection` was added to the Dasharo Security Options menu, which disables all writes to flash, except for writes from SMM which are necessary for EFI variables to work. It's recommended to enable it for security when a password is set, but it needs to be disabled when updating the BIOS.

![image](https://user-images.githubusercontent.com/3678707/198617581-1f915efa-8b05-4c74-b45c-e23fdbc0ef5b.png)
