### ISSUE TITLE
Incorrect recognition of the device connected by Display port on Windows 11 vp46xx v1.0.16

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#163]
**Dasharo version**
 v1.0.16

**Dasharo variant**
Protectli vp46xx

**Affected component(s) or functionality**
Display Port

**Brief summary**
The device connected via Display Port is recognized incorrectly.

**How reproducible**
100%

**How to reproduce**

1. Boot into Windows 11.
2. Open power shell with administrator privileges.
3. Run the command `Get-WmiObject WmiMonitorConnectionParams -Namespace root/wmi`

**Expected behavior**
`VideoOutputTechnology : 10` or `VideoOutputTechnology : 11` - recognized as Display Port

**Actual behavior**
`VideoOutputTechnology : 2147483648` - recognized as internal LCD

**Screenshots**

**Additional context**

**Solutions you've tried**
Some test with additional monitor connected via HDMI-port and changing screens

**Comment by miczyg1** [comment]
I don't think we can change it. The eDP liens from CPU are connected to the DisplayPort you are testing according to the platform schematics. eDP lines are typically used for LCDs. As it is fixed in the hardware design I would mark it as expected behavior for this particular platform. But good catch anyway.

**Comment by macpijan** [comment]
So it looks like we need to adjust expected strings for this boards.

**Comment by Pokisiekk** [comment]
Thanks for answer, I will adapt tests and think that I can close this issue.
