### ISSUE TITLE
MSI PRO Z690-A: Add the CH341A to the documentation as an inexpensive recovery option

### ISSUE THREAD

**Issue by renehoj** [Dasharo/dasharo-issues#178]
**The problem you're addressing (if any)**
The documentation doesn't have a cheap and "easy" recovery option if you brick your motherboard

**Describe the solution you'd like**
The CH341A SPI combined with a WSON test probe can be used as an external programmer to flash the MSI Z690 firmware, without soldering any wires to the motherboard. I believe this is easier for someone who doesn't have the skills or equipment to solder wires to the motherboard, and the total price is around $30 on eBay.

**Where is the value to a user, and who might that user be?**
This is an "easy" and inexpensive option for someone who just needs to flash the firmware once to recover a bricked motherboard. 

**Describe alternatives you've considered**

**Additional context**
The hand held WSON probe can be difficult to work with, but I still think it's a good option for someone who only needs to flash the ROM once.

**Comment by pietrushnic** [comment]
Definitely related to: https://github.com/Dasharo/dasharo-issues/issues/178

**Comment by miczyg1** [comment]
Guide added: https://github.com/Dasharo/docs/pull/316
https://docs.dasharo.com/variants/msi_z690/recovery/

**Comment by Firminator** [comment]
@renehoj Can you let us know which exact jumperwires you bought and which WSON8 probe? A link to a product on Amazon or ebay would be preferable. Thanks.

**Comment by renehoj** [comment]
https://www.ebay.com/itm/354449260945

This is very similar to the one I have, the wires are connected to the probe and protected by a heat shrinking tubing sleeve. I can't remember if the one I have is 6x8mm with 1.27mm spacing, but I think it is.

https://www.ebay.com/itm/354449260945

I'm using standard dupont female to female jumper wires.


But read the updated recovery guide, it shows all the items you need, including how you down convert the voltage.
https://docs.dasharo.com/variants/msi_z690/recovery/

**Comment by Firminator** [comment]
Thanks. That was helpful.

Gathering info from Mical and renehoj and zirblazer and others and some of my own research...

There seems to be a bunch of chip packaging types accd. to https://wikiless.org/wiki/List_of_integrated_circuit_packaging_types?lang=en#Small_outline_packages

Acronym | Full name | Remark
-- | -- | --
SOP | Small-outline package[1] |  
CSOP | Ceramic small-outline package |  
DSOP | Dual small-outline package |  
HSOP | Thermally-enhanced small-outline package |  
HSSOP | Thermally-enhanced shrink small-outline package[16] |  
HTSSOP | Thermally-enhanced thin shrink small-outline package[16] |  
mini-SOIC | Mini small-outline integrated circuit
MSOP | Mini small-outline package | Maxim uses the trademarked name µMAX for MSOP packages
PSOP | Plastic small-outline package[3] |  
PSON | Plastic small-outline no-lead package |  
QSOP | Quarter-size small-outline package | The terminal pitch is 0.635 mm.[3]
SOIC | Small-outline integrated circuit | Also known as SOIC NARROW and SOIC WIDE
SOJ | Small-outline J-leaded package
SON | Small-outline no-lead package |  
SSOP | Shrink small-outline package[3] |  
TSOP | Thin small-outline package[3] |  
TSSOP | Thin shrink small-outline package[3] |  
TVSOP | Thin very-small-outline package[3] |  
VSOP | Very-small-outline package[16] |  
VSSOP | Very-thin shrink small-outline package[16] | Also referred as MSOP = micro small-outline package
WSON | Very-very-thin small-outline no-lead package |  
USON | Very-very-thin small-outline no-lead package | Slightly smaller than WSON

So even within a packing type there are differences. WSON has apparently 2 different measurements. Comes with 8x6mm and 6x5mm
![](https://user-images.githubusercontent.com/12078737/209387748-e00c2622-353e-4386-9871-a4f09b3b7377.jpg)

MSI Z670 has BIOS chip WSON 8mmx6mm with 1.27mm spacing between the pins. So we need a WSON 8x6 probe.
You can't use a Ponoma 5250 because it's for SOIC chip packaging type so it wouldn't fit the WSON chip on the MSI Z670 mobo.
