### ISSUE TITLE
The power LED is not always blinking while in sleep mode on Windows 11 NS50/70 NV4X v1.3.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#182]
**Dasharo version**
v.1.3.0., v.1.4.0

**Dasharo variant**
NS50/70, NV41MZ, NV41MB, NV41PZ

**Affected component(s) or functionality**
The power LED, sleep mode

**Brief summary**
The power LED is permanently green or blinks with variable frequency during sleep mode on Windows 11

**How reproducible**
2% - permanently green
100%(If already blinks) - blinks with variable frequency

**How to reproduce**

1. Power on the laptop.
2. Boot into Windows 11.
3. Close the lid or press `Fn+F12` or press power button.

**Expected behavior**
The laptop is in sleep mode, the power LED blinking green

**Actual behavior**
The laptop is in sleep mode, the power LED blinks with variable frequency. The power LED start blinks after 10-25 seconds.
In some cases the power LED is permanently green.

**Screenshots**

**Additional context**
Closing the lid during sleep mode, causes the power LED stop blinking and start again after 10-25 seconds.

**Solutions you've tried**

**Comment by mkopec** [comment]
Some information to help fixing this later:

The variable frequency bliking is a side effect of how the EC handles sleep detection - Windows periodically wakes up to do Windows things which causes SLP_S0# to deassert, which in turn causes a reset of the LED blinking timer. This should probably be handled in EC firmware. The laptop is still asleep as indicated by PowerhouseMountain.

The LED not blinking at all may be caused by the same wakeups occuring at a higher frequency, or may indicate a lack of sleep whatsoever. PHM should indicate the actual sleep residency.

**Comment by wessel-novacustom** [comment]
I am wondering if the laptop is indeed in sleep mode (S3 or modern standby) if this problem occurs? Otherwise we will probably get battery draining problems while in sleep mode?

**Comment by macpijan** [comment]
> I am wondering if the laptop is indeed in sleep mode (S3 or modern standby) if this problem occurs? Otherwise we will probably get battery draining problems while in sleep mode?

According to `The laptop is still asleep as indicated by PowerhouseMountain.` - it is, but please confirm @mkopec

**Comment by macpijan** [comment]
@wessel-novacustom also reports that on NS5x/NS7x with Windows 11 Pro he observes following:

```
LED remains green, it looks like the laptop doesn’t go in sleep mode after FN+F12. The FN+1 fan swith can be triggered and the keyboard backlight remains on (if it was turned on before sleeping).

Tested on NS51MU running Windows 11 Pro.
```

**Comment by mkopec** [comment]
With modern standby it's important to have **all** device drivers installed. All drivers are available via Windows Update - however, some of them need to be selected manually via the `Advanced options -> Optional updates` submenu in Windows Update settings.

**Comment by wessel-novacustom** [comment]
Copied that. This is our standard procedure. As Windows 11 Pro 22H2 has been released, we will create new images and try again with a clean install of that version, including the optional updates. I will be back soon with the outcome.

**Comment by Pokisiekk** [comment]
After installing all the updates and drivers on Windows 11 and doing some tests on the NV41MZ and NS70MU, I updated the issue description.

**Comment by Pokisiekk** [comment]
After installing `nvidia-driver-515` and `nvidia-dkms-515 ` on Ubuntu 22.04 on NV41MB power LED during sleep works properly. We will add info about it to [Post-installation steps](https://docs.dasharo.com/variants/novacustom_nv4x/post_install/) before release.

**Comment by wessel-novacustom** [comment]
Sounds good! :-)

**Comment by macpijan** [comment]
I've been testing one of the units for the last couple of days with Windows 11. The LED blinks as expected. The battery charge drop is also fine - drops from 100% to 50-60% over 24 hours.

I've had problem **once** that the LED was constantly ON and battery was dropping significantly faster. I cannot reproduce this anymore, however. This needs to be monitored.

**Comment by macpijan** [comment]
`NV40MB 1` v1.4.0. Cannot reproduce the issue, although it sometimes can take up to a few minutes to go into suspend fully. Especially shortly after Windows start.

**Comment by macpijan** [comment]
Any instances of this problem in recent testing?

**Comment by Pokisiekk** [comment]
@macpijan Yes, the problem simply occurs on the latest firmware versions and it looks like it is described in the section `How reproducible`

**Comment by miczyg1** [comment]
Here we write that the LED and sleep works correctly:
https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1273440508
https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1274245963
https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1443866666

But at the end we write that the issue still occurrs: https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1521366158

Then what is it finally? I suspect the test failing is https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr018002-keyboard-function-key-sleep-in-os-windows-11 because there is no other test for sleep on Windows 11, despite there are two different suites for this covering Linux only:
https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31M-platform-suspend-and-resume/
https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31J-sleep-mode/

Does this test https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr018002-keyboard-function-key-sleep-in-os-windows-11 assume that:
1. Drivers are installed? https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1263752177 https://github.com/Dasharo/dasharo-issues/issues/182#issuecomment-1273440508 Step 2 in Test setup indicates drivers should be installed.
2. Windows is fully loaded before trying to go to sleep? I.e. we don't try to put the laptop to sleep right after logging in? It would be an absurd to require the sleep to work immediately after logging into Windows, while it hasn't loaded fully yet. It is not S3 suspend! Windows still does a lot of job after logging, so don't expect it to go to sleep properly a few seconds after login... The test is written in such a manner that it immediately calls the tester to use the sleep key after logging in. As you can see, you need at least half a minute to let Windows finalize booting tasks. S0i in the S0ix means S0 IDLE! So first you need to let the OS start idling to make sleep work!

The test case needs an update for the S0ix sleep testing. S3 testing will not require this, because S3 is fundamentally different. S0ix has a bunch of HW requirements to happen first befoe sleep is possible. With S3 you just transition to sleep on a whim whenever you need.
