### ISSUE TITLE
Procedure for MSI recovery does not have TPM header pinout

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#188]
To recover MSI one have to go to MSI manual and find picture of the header to make correct connectivity. This should not be the case. Easiest fix is just screenshot datasheet and paste it in correct location in recovery manual.

**Comment by miczyg1** [comment]
@pietrushnic https://github.com/Dasharo/docs/pull/649

**Comment by pietrushnic** [comment]
Damn, I don't remember where I get this issue from, so I wonder how I can approve that PR if I can't test it. Do you have any evidence or I should trust you? Maybe @macpijan or @johanes2115 can confirm documentation?

**Comment by miczyg1** [comment]
> Damn, I don't remember where I get this issue from, so I wonder how I can approve that PR if I can't test it. Do you have any evidence or I should trust you? Maybe @macpijan or @johanes2115 can confirm documentation?

I recall the connection to the header was only presented in the table in the MSI development section. Then I have found out the CS pin is also present on the JTPM1 header and added a photo: https://github.com/Dasharo/docs/commit/e0883909f8209742e6431ad563c608e1f15b3f86 so your request should be addressed already, if not the fact that you mention recovery. The recovery section still had the CH341a with WSON8 probe method, which was not in lien with what was described in development section. So the PR aligns recovery section with development section and adds the missing JPTM1 header picture which the issue is about. @pietrushnic

**Comment by pietrushnic** [comment]
@miczyg1 ok, I marged it.
