### ISSUE TITLE
Standardize TPM and measured boot support in coreboot

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#227]
Basically it is a reference issue to: https://ticket.coreboot.org/issues/420#change-1174

**Comment by macpijan** [comment]
The discussion on ML started here: https://mail.coreboot.org/hyperkitty/list/coreboot@coreboot.org/thread/GIZRCO42OYWEFPC62OJ47IF5V2EARR5I/

We found that to be some sort of a problem for the first time, when adding TPM support for POWER9

**Comment by rafkoch** [comment]
@SergiiDmytruk your issue is in TO DO column in project [Nlnet October 2022](https://github.com/Dasharo/dasharo-issues/projects/5#card-86225608). 
My questions are:
1. What are you currently doing in this task? Maybe we should move them to the IN PROGRESS column?
2. What are the next steps and products in this task planned to complete it?

**Comment by SergiiDmytruk** [comment]
Yes, this is in progress. It's these patches https://review.coreboot.org/c/coreboot/+/68752, which are under review by upstream with 2 being merged by now.

**Comment by rafkoch** [comment]
@SergiiDmytruk so, the last thing is to wait for review + merge.
So I added a link to this, not merged patch to internal JIRA to track the upstream proccess.
With this action, I decided to close this issue on Github. 
Thank You for Your engagement @SergiiDmytruk
