### ISSUE TITLE
"Disable Secure Boot" section does not belong to DTS documentation

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#253]
**Affected component(s) or functionality**

docs

**Brief summary**

This section: https://docs.dasharo.com/dasharo-tools-suite/documentation/#disabling-secure-boot
has nothing to do with DTS.
It should be in Dasharo Setup menu guide or something like that, and linked there.

**Comment by wessel-novacustom** [comment]
@macpijan 

I think it is relevant for DTS as UEFI Secure Boot needs to be disabled in order to boot DTS (at least from iPXE), so please consider to either [link to the Knowledge base](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration) or to keep this as it is and to close the issue.

**Comment by PLangowski** [comment]
@macpijan Are you suggesting creating a new guide and moving this section there?

**Comment by m-iwanicki** [comment]
@macpijan Is linking to [Secure Boot Configuration](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration) in requirements enough?

**Comment by macpijan** [comment]
> @macpijan Is linking to [Secure Boot Configuration](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration) in requirements enough?

Yes, I think so.
