### ISSUE TITLE
Modify ec_transition script, add support for ADL devices and possibility to flash EC from cmdline

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#255]
**The problem you're addressing (if any)**

The script now does not support ADL devices, also it would be nice to have possibility to flash EC provided from cmdline. See [1]

[1] https://github.com/Dasharo/docs/pull/356#discussion_r1011774947

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by artur-rs** [comment]
needs @TomaszAIR confirmation if it's still relevant

**Comment by TomaszAIR** [comment]
@artur-rs IIRC only TGL needs this ec_transition script. In case of ADL, they are delivered with EC that we can easily update using ectool. @mkopec could you confirm that?

**Comment by artur-rs** [comment]
@TomaszAIR @mkopec thanks. To summarize and confirm:
1. TGL-based laptops are supported by the ec_transition script, so this issue is irrelevant to those platforms (in other words, we shouldn't change the title/description of this issue)?
2. If ADL laptops can be configured by the ectool, do we have documentation on how to do that (docs.dasharo)? If not, maybe an external guide is adequate for this purpose.

**Comment by TomaszAIR** [comment]
@artur-rs I do not think we need to document anything, ADL comes with open EC, so while updating/deploying we are using ectool in scripts https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L452. I think this issue was started before we knew that ADL will have open EC.
