### ISSUE TITLE
MSI PRO Z690-A DDR5 coreboot support 13th gen intel processors

### ISSUE THREAD

**Issue by louregni** [Dasharo/dasharo-issues#263]
Any plan to support 13th gen intel processors in the coreboot implementation of this board ?

I plan to use this board with a new gen processor if possible.

**Comment by 6d6178667269747a** [comment]
@zirblazer , you don't need the new FSP. I already booted ubuntu 22.10 with the alderlake FSP on a MSI PRO Z690-A DDR5 with an Intel i9 13900k. But you need the DDR5 patch from here
https://review.coreboot.org/c/coreboot/+/68448

and my raptorlake patch with an updated intel-microcode repo. (no warranty)
[raptorlake_s_coreboot_patch.txt](https://github.com/Dasharo/dasharo-issues/files/9996230/raptorlake_s_coreboot_patch.txt)

**Comment by miczyg1** [comment]
> @zirblazer , you don't need the new FSP. I already booted ubuntu 22.10 with the alderlake FSP on a MSI PRO Z690-A DDR5 with an Intel i9 13900k. But you need the DDR5 patch from here https://review.coreboot.org/c/coreboot/+/68448

@6d6178667269747a I don't know here your confidence come from about not needing RPL FSP. I wouldn't be so sure that ADL FSP does everything necessary for RPL CPUs. I mean, yeah, those two CPUs are pretty similar, but stil you may experience some issues due to some missing configuration. Intel hopefully will update ADL FSP by adding RPL support to it (that would be the most reasonable way).

**Comment by pietrushnic** [comment]
@6d6178667269747a congratulations for testing RPL. Since you are very active here we wonder what we should do with your contributions.

* Since you dropped patch here I guess you cannot accept [DCO](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) for coreboot?
* Can we contact you off-github e.g. matrix?
* Does it make sense for you to give you credit for the work using Twitter or some other social media?
* Would you be able to join future Dasharo community call or vPub to share your thoughts (no recording, no registration, no video needed)?

Finally, I ask this question everywhere where significant contribution or interest is shown, what is your use case for Dasharo? As you know we trying to gather information about workloads used by community to push project in correct direction. What would be most wanted features for you?

**Comment by 6d6178667269747a** [comment]
@pietrushnic ,
- what exactly do you mean by accepting DCO for coreboot? The patch i submitted is free to use (MIT licensed).
- you can contact me on github PM and i can send you my matrix contacts there.
- no need for credit on twitter or other social platform.
- vPub sounds nice.

I'm using my coreboot machine for gaming and as beefy workstation. Nice to haves would be fan control, voltage control and a libgfxinit support. 

Currently I'm working on a proper linuxboot (linux, u-root) configs to boot my Archlinux. Future plans are to also build the FSP from scratch and include into my coreboot image (fsp-m first).

**Comment by miczyg1** [comment]
> what exactly do you mean by accepting DCO for coreboot? The patch I submitted is free to use (MIT licensed).

I believe @pietrushnic assumed that you cannot accept DCO for coreboot, since you didn't push your patch to [coreboot's gerrit](https://review.coreboot.org/) for review to get it merged upstream.

> I'm using my coreboot machine for gaming and as beefy workstation. Nice to haves would be fan control, proper XMP > support, voltage control and a libgfxinit support. I hacked XMP in with:
> 
> memupd->FspmConfig.SpdProfileSelected = 2; // XMP profile 1
> 
> and it worked, but this is ugly.

There is nothing ugly nor pretty here. That's what one would normally do, although it would be great to have XMP runtime configurable indeed.

**Comment by pietrushnic** [comment]
@6d6178667269747a 

* IANAL, but AFAIK we cannot use MIT code in GPLv2 licensed code.
* [coreboot DCO](https://www.coreboot.org/Development_Guidelines#Sign-off_Procedure) prevent anonymous contribution
* [GitHub removed private messaging](https://stackoverflow.com/a/12687679) some time ago
* please reach me through matrix @pietrushnic:matrix.org

**Comment by pierinogiorgio** [comment]
I bump the initial request as I have the same need to use a gen13 processor (i9-1300k).

**Comment by miczyg1** [comment]
It will probably not happen earlier than mid February.

**Comment by LTS-Colonel** [comment]
I rushed to buy new hardware for a Z690-A DDR5-based PC when I learned of Coreboot support...without looking into whether or not the i9-13900K was supported yet. Woops.

No intention to rush the Dasharo team but is it possible to speculate whether or not 13th Gen support might **not** happen? If so I may still be able to return it in favor of a 12th Gen.

_Enormous_ thank you for your development efforts!

**Comment by miczyg1** [comment]
@LTS-Colonel, we will soon start the work on 13th gen. If you are not in a hurry, you may keep your i9-13900K

**Comment by zirblazer** [comment]
Is not going to work. Dasharo is specifically for the MSI PRO Z690-A (DDR5) or PRO Z690-A DDR4 (Either standard or WIFI versions). That board size is full ATX and doesn't fit in an ITX case.

**Comment by RyzeNGrind** [comment]
> Is not going to work. Dasharo is specifically for the MSI PRO Z690-A (DDR5) or PRO Z690-A DDR4 (Either standard or WIFI versions). That board size is full ATX and doesn't fit in an ITX case.
> There is an user with a GeForce 4090 (A MSI GAMING X TRIO 24G specifically) working with Dasharo.

Is there any way i can help contribute to making this work on the mini ITX case?

**Comment by artur-rs** [comment]
Adding the scope (from NLnet application) that will be covered in the next release:

The first part of development will require implementing Raptor Lake-S CPU support in coreboot. coreboot already supports Raptor Lake-P mobile CPUs but support for their desktop counterparts has not yet been implemented. These tasks include: setting up microcode updates, implementing processor and PCH identification, implementation of platform settings, such as power limits and voltage regulator parameters, in accordance with Intel reference values that will allow us to launch FSP. The changes shall be tested on existing MSI PRO Z690-A DDR4/DDR5 board and the freshly enabled MSI PRO Z790-P.

**Comment by miczyg1** [comment]
Set of patches that implement RPL-S (13th gen) support:

https://review.coreboot.org/c/coreboot/+/69798
https://review.coreboot.org/c/coreboot/+/76203
https://review.coreboot.org/c/coreboot/+/76191
https://review.coreboot.org/c/coreboot/+/76192
https://review.coreboot.org/c/coreboot/+/76204

13th gen support will be available in a pre-built binary for subscribers in the incoming v1.1.2 release. For non-subscribers, building from source code will also be possible.
