### ISSUE TITLE
DTS uses incorrect Dasharo deployment procedure for MSI platforms

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#316]
**Dasharo version**
Any

**Dasharo variant**
Dasharo compatible with MSI PRO Z690-A DDR4/DDR5

**Affected component(s) or functionality**
DTS

**Brief summary**
DTS does not comply with deployment documentation: https://docs.dasharo.com/variants/msi_z690/initial-deployment/
The documentation forbids powering off the platform:

```
IMPORTANT! After the command succeeds, invoke sudo reboot or click the reboot/restart in the GUI to reboot the board. Press ENTER when prompted on the screen to remove the installation media (if Ubuntu live is used). DO NOT POWEROFF THE BOARD as SMI handlers of original MSI firmware may overwrite flash contents and cause a brick.
```

**How reproducible**
Always: https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L523

**Expected behavior**
After Dasharo deployment on MSI platform, a reboot should happen.

**Actual behavior**
After Dasharo deployment on MSI platform, a power off is issued.

**Additional context**
Discovered via bricked platform on Matrix.

**Comment by TomaszAIR** [comment]
Fixed in v1.1.1 DTS release https://docs.dasharo.com/dasharo-tools-suite/releases/#v111-2023-02-20, please look at release notes, from now on, the default behavior is to execute reboot after initial deployment.

In the near future we plan to provide test results with every DTS release on defined list of platforms, so then we could prepare one which will test that reboot was used.
