### ISSUE TITLE
Keyboard backlight brightness is not properly restored after cold-boot

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#402]
**Dasharo version**
v1.6.0

**Dasharo variant**
NS50PU, NS70PU

**Affected component(s) or functionality**
Keyboard backlight brightness, clod-boot

**Brief summary**
Keyboard backlight brightness after cold-boot is restored to the state at the beginning of boot before first cold-boot on Ubuntu 22.04.

**How reproducible**
100%

**How to reproduce**

1. [ECR025.002](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr025002-permanent-keyboard-illumination-after-cold-boot-ubuntu-2204)

**Expected behavior**
After cold-boot keyboard backlight brightness and colors settings remain the same.

**Actual behavior**
After cold-boot only the keyboard backlight color remain the same.
Keyboard backlight brightness is restored to the state at the beginning of boot before first cold-boot.
An example scenario:
1. Set brightness=2 color=green -> reboot -> brightness=2 color=green
2. Set brightness=3 color=pink -> cold-boot -> brightness=2 color=pink
3. Set brightness=4 color=red -> cold-boot -> brightness=2 color=red
 
**Screenshots**

**Additional context**
On Windows 11 it works fine.

**Solutions you've tried**

**Comment by Psotas** [comment]
**Dasharo version**
v1.7.2

**Dasharo variant**
NS70PU

**How to reproduce**

Steps to reproduce the behavior:
[ECR025.002 (ubuntu)](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr025002-permanent-keyboard-illumination-after-cold-boot-ubuntu-2204)
[ECR025.003 (windows)](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr025003-permanent-keyboard-illumination-after-cold-boot-windows-11)

**Expected behavior**
After cold-boot keyboard backlight brightness and colors settings remain the same.

**Actual behavior**
After cold-boot keyboard backlight brightness and colors settings is default(?).

**Additional context**
Same for firmware (but this is not in platform tests scope) [ECR025.001 (firmware)](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio/#ecr025001-permanent-keyboard-illumination-after-cold-boot-firmware)

**Comment by mkopec** [comment]
Doing an unclean shutdown will prevent the setting from being saved. This is the same exact underlying issue as https://github.com/Dasharo/dasharo-issues/issues/524

If you do a proper shutdown with the battery attached, the settings will be preserved across boots.
