### ISSUE TITLE
Full migration of the Dasharo test infrastructure source code to Dasharo/open-source-firmware-validation

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-issues#468]
**Dasharo version (if applicable)**

All versions

**Dasharo variant (if applicable)**

All variants

**Affected component(s) or functionality (if applicable)**

Firmware release process

**Brief summary**

We should fully publish whole source code of the Dasharo test infrastructure to the already initialised repository (with first test-cases/test-suites) [Dasharo/open-source-firmware-validation](https://github.com/Dasharo/open-source-firmware-validation).
Appropriate cleanup and changes are needed.

This issue should be treated as a place for discussion about planned tasks and actual status of the migration. All confirmed subtask should be added as a checklist in this issue or standalone issues linked here. We can also add milestone if this will be required.

**Additional context**

* target repo: https://github.com/Dasharo/open-source-firmware-validation
* additional work related to all supported submodules like:
  * https://github.com/3mdeb/pikvm-rest-api
  * https://github.com/3mdeb/rtectrl-rest-api
  * https://github.com/3mdeb/sonoff-rest-api
  * https://github.com/3mdeb/testing-stands
  * snipeit-api - TBD
* sync with https://github.com/Dasharo/docs documentation

**Comment by pietrushnic** [comment]
@artur-rs @macpijan I think the best way would be to give the ability for the community to run tests. IMHO that is critical because if the community can run tests, we can get feedback and fix tests or extend their scope if needed. We can implement test-driven bug fixing.

So at least from my perspective, we should think about the following users of open-source firmware validation repo and associated documentation:

* community members who want to confirm some features work or they want to report a bug - in the long run, those who would like to pass Dasharo Certification Program
* Dasharo Validation Team - for release and bug fixes validation, as well as for test-driven bug fixing
* Dasharo Development Team - for providing proof that given features were correctly implemented

So assuming I'm like a community member. I have some sets of hardware, supported or with planned support in Dasharo:
* Supermicro X11SSH - we should cover both firmware and OpenBMC. Further, one has tested in Robot Framework, so those should be integrated or run separately. Power control can be done by BMC.
* PC Engines apu2 - should be relatively easy to use without RTE, especially with WoL
* Dell OptiPlex 7010/9010 - SSH tests, I doubt we have any other methods
* QEMU - this is very important since it is pure software testing
I would like to run tests on that hardware to confirm the Dasharo features set or develop additional tests to confirm new features or bug fixes. That means we need very specific instruction, as automated and minimal as possible, to prepare the above hardware for testing (aka running Robot Framework scripts from open-source firmware validation repo).

IIUC's key problem is an interface. The open-source firmware validation repo has too many assumptions about the hardware configuration. There are requirements for Sonoff and RTE so that test can be run only in the Dasharo Transparent Validation lab infrastructure. This is not acceptable, IMHO. We should offer various levels of complexity:
* fully featured hardware configuration can perform a fully featured set of tests
* "I have just serial cable and can connect it to another computer" - in this case, we don't support everything, but a substantial amount of tests
* just SSH connection for some configurations. This should be enough to perform some test cases, coverage is small, but still, there is quite a lot to do and extend

More to that, there are assumptions about the infrastructure in which tests can be run (e.g. iPXE, NFS).

Let's say we will overcome the above, then we have to clearly say what can be done with the results since those are evidence of implementation. We should offer that as value-added content for Dasharo Entry Subscribers.

**Comment by pietrushnic** [comment]
@macpijan there should be quite a lot of progress here. Can we improve this ticket?

**Comment by macpijan** [comment]
All tests and keywords we had are already published in: https://github.com/Dasharo/open-source-firmware-validation
Tests development fully relies on this, and other open-source repositories linked in the issue description - there are no closed parts anymore.

The goal from the title: `Full migration of the Dasharo test infrastructure source code to Dasharo/open-source-firmware-validation` is already there, IMHO. If there are specific requests for new features, let's submit concrete new tickets for them.

**Comment by macpijan** [comment]
@pietrushnic Sorry, I have not missed your comment, rather focused on the issue title when closing it.

Trying my best to unveil your ideas below.

> I think the best way would be to give the ability for the community to run
> tests. IMHO that is critical because if the community can run tests, we can get
> feedback and fix tests or extend their scope if needed. We can implement
> test-driven bug fixing.

OK

> So at least from my perspective, we should think about the following users of
> open-source firmware validation repo and associated documentation:
> 
> 1. community members who want to confirm some features work or they want to report a bug - in the long run, those who would like to pass Dasharo Certification Program
> 2. Dasharo Validation Team - for release and bug fixes validation, as well as for test-driven bug fixing
> 3. Dasharo Development Team - for providing proof that given features were correctly implemented

OK

> So assuming I'm like a community member. I have some sets of hardware,
> supported or with planned support in Dasharo:
> 
> 1. Supermicro X11SSH - we should cover both firmware and OpenBMC. Further,
> one has tested in Robot Framework, so those should be integrated or run
> separately. Power control can be done by BMC.
> 2. PC Engines apu2 - should be relatively easy to use without RTE, especially with WoL
> 3. Dell OptiPlex 7010/9010 - SSH tests, I doubt we have any other methods
> 4. QEMU - this is very important since it is pure software testing

1. If platform has OpenBMC support, we should be able to provide ability to
perform full testing with no additional HW setup. X11SSH might not be the best
bet right now, as we are not close to releasing something for that one.

2. PC Engines is not supported at all at the moment in OSFV. Adding it back should not be
a huge task, though. I will put Protectli and possibly other similar router boxes
in this category.

For this category, I am not fully convinced on the WoL, though. WoL would not be
able to provide any kind of reliability when it comes to putting platform into
expected start state. Even adding "manual" power control (display information to
the user to power cycle, and wait until it happens) would be more reliable).
And also, already Supported Sonoff costs $10, being quite a popular (so should
be feasible to source) all over the world.

> I would like to run tests on that hardware to confirm the Dasharo features set
> or develop additional tests to confirm new features or bug fixes. That means we
> need very specific instruction, as automated and minimal as possible, to
> prepare the above hardware for testing (aka running Robot Framework scripts
> from open-source firmware validation repo).

This is not there, we need that for each supported hardware. We have some for:
https://docs.dasharo.com/variants/asus_kgpe_d16/setup/
This is quite specific, but not that minimal.

> IIUC's key problem is an interface. The open-source firmware validation repo
> has too many assumptions about the hardware configuration. There are
> requirements for Sonoff and RTE so that test can be run only in the Dasharo
> Transparent Validation lab infrastructure. This is not acceptable, IMHO. We
> should offer various levels of complexity:

This is not really a **key** problem, IMHO. That is configurable and we can
generate configs for different kind of setup. It is a matter of adding support
for different kind of power control devices. Right now only the mentioned RTE,
Sonoff (and to some extent OpenBMC) are supported.

The interface to OSFV is:
- serial over telnet - required for many of the tests
- power control - required for most of the tests
  - this includes cutting off the power line, and if no auto power-on is present, also power button control is required
- external flashing - only a few tests need it

> 1. fully featured hardware configuration can perform a fully featured set of tests
> 2. "I have just serial cable and can connect it to another computer" - in this case, we don't support everything, but a substantial amount of tests
> 3. just SSH connection for some configurations. This should be enough to perform some test cases, coverage is small, but still, there is quite a lot to do and extend

1. Fully supported be the given platform - sure
2. Yes, this can be done. We
just need serial over telnet and some power control. ser2net can be installed
locally, probably as a container as well. For the power control, I would not
recommend WoL, but the "manual" method instead. You would:
- run some test with "manual power control" flag, or config,
- it would start and instruct you what needs to be done, waiting for you to do
  it (such as remove power cord, wait 10s, connect back)
- the test would run, and you could report the results to a bug request, and so on

This may be not ideal, but I assume such users would not run hundreds of tests,
but just a few, so manual work should not be that bad, and would provide great
reliability and much less problems than e.g. trying with WoL.

On top of that, I think at this point we should rework the platform configs, so the can share
more parts and users can generate one for themselves (as when they are using different peripherals, and so on).

> More to that, there are assumptions about the infrastructure in which tests can
> be run (e.g. iPXE, NFS).

No idea how to comment that. That is probably not the case anymore - we do not
rely on the internal iPXE/NFS server AFAIK. We rely on SnipeIT, but there is already
a flag for that.

> Let's say we will overcome the above, then we have to clearly say what can be
> done with the results since those are evidence of implementation. We should
> offer that as value-added content for Dasharo Entry Subscribers.

You mean publishing test results?

**Comment by pietrushnic** [comment]
> @pietrushnic Sorry, I have not missed your comment, rather focused on the issue title when closing it.

@macpijan Sure, thank you for taking the time and reply.


> If platform has OpenBMC support, we should be able to provide ability to perform full testing with no additional HW setup. 

Do we have examples to follow, or can we create items on the OSFV roadmap to deliver such integration examples? If not we should probably add it to roadmap for next release.

> X11SSH might not be the best bet right now, as we are not close to releasing something for that one.

I can't think of any server platform that can compete with this hardware in terms of feasibility. So we don't have an alternative for now, but we also don't have motivation or resources for X11, so that we can give it up as the target for now.
 
> PC Engines is not supported at all at the moment in OSFV. Adding it back should not be a huge task, though. I will put Protectli and possibly other similar router boxes in this category.

Great, thank you.

> For this category, I am not fully convinced on the WoL, though. WoL would not be
able to provide any kind of reliability when it comes to putting platform into
expected start state. Even adding "manual" power control (display information to
the user to power cycle, and wait until it happens) would be more reliable).
And also, already Supported Sonoff costs $10, being quite a popular (so should
be feasible to source) all over the world.

I understand and agree. I guess we already have Sonoff control API. Ideally, we would have something non-WiFi, but after doing some research, I cannot find anything more reasonable than a web power switch, which a US power plug may also be problematic to use. To sum up, we should support the manual method, snooff, and RTE. We probably should add a modular selection of power control methods as well as support for manual power control on our roadmap.

> This is not there, we need that for each supported hardware. We have some for:
https://docs.dasharo.com/variants/asus_kgpe_d16/setup/
This is quite specific, but not that minimal.

Yes, and we also have: https://docs.dasharo.com/transparent-validation/msi-z690/laboratory-assembly-guide/
Depending on our priorities, we should add further information for existing or newly supported platforms, maybe as part of v0.1.0 requirements. It has to be part of the standard Dasharo Community Support road mapping, so essentially, all hardware platforms on the DCS roadmap need that part of the documentation.

> This is not really a key problem, IMHO. That is configurable and we can
generate configs for different kind of setup. It is a matter of adding support
for different kind of power control devices.

Ok, so I assume we agree on adding that to OSFV roadmap.

> On top of that, I think at this point we should rework the platform configs, so the can share
more parts and users can generate one for themselves (as when they are using different peripherals, and so on).

Agree.

> No idea how to comment that. That is probably not the case anymore - we do not
rely on the internal iPXE/NFS server AFAIK. We rely on SnipeIT, but there is already
a flag for that.

I saw that in some tests/keywords, but maybe we don't use those e.g. [Get Firmware Version](https://github.com/Dasharo/open-source-firmware-validation/blob/main/keywords.robot#L384), [LBT002.001](https://github.com/Dasharo/open-source-firmware-validation/blob/main/dasharo-compatibility/ubuntu-debian-support.robot#L92)

> You mean publishing test results?

Precisely, how end users may use test results except for reporting issues, which is obvious. I would expect something like HCL for features e.g. Qubes OS already has something like that https://www.qubes-os.org/hcl/ where you claim about platform hardware working or not. I would envision a community-contributed test results database/spreadsheet if we can reach usability acceptable by that group. The community also should be able to extend the scope of compatibility by adding/improving tests. The point is to run user tests even on non-Dasharo to have a comparison, and benchmark that can convince to buy DES. Our first challenge would be to execute that for UEFI Secure Boot on various UEFI BIOS implementations.
