### ISSUE TITLE
Fan is louder in `Silent` mode than it is with `1.3.0` ec rom.

### ISSUE THREAD

**Issue by Ferenc-** [Dasharo/dasharo-issues#532]
### Device

NS 51 TGL

### Dasharo version

1.4.0

### Affected component(s) or functionality

Fan is louder in `Silent` mode than it is with `1.3.0` ec rom.

### Brief summary

Fan is louder in `Silent` mode than it is with `1.3.0` ec rom.

### How reproducible

The issue occures non stop, provided that the unit is not under heavy load, in which the fan would spin up anyway.

### How to reproduce

1. get NS 51 TGL
2. flash the 1.4.0 ec rom
3. set the profile in BIOS to `Silent`
4. Hear the noise from the fan louder than on 1.3.0

### Expected behavior

The fan is at least as silent as with the `1.3.0` ec rom.

### Actual behavior

Fan is louder than with previous ec rom version.

**Comment by mkopec** [comment]
@Ferenc- To clarify, does the issue appear at low loads, when the fan is stopping or starting? If so, you could try setting the fan mode to `Performance` and see if that works around the issue.

If that is the issue, then we may need to raise the minimum fan speed in the silent fan mode to prevent the fan from stopping and starting constantly.

**Comment by wessel-novacustom** [comment]
Back in the days, we used to replace the fans of these models with fans that are more silent, but they turned out to be less performing as well. The proprietary EC firmware we used then had an aggressive fan profile, causing the fan to be very disturbing. Since we have Dasharo firmware with adjusted fan profiles, replacing the fan is no longer necessary. Moreover, the fan behaviour becomes even less aggressive with the latest fan profile our team is working on.

To check your fan type, please contact the NovaCustom support team directly and let them know your order number. The fan replacement back to the original one will be done for free under warranty within 5 working days (transit time not included). EU customers get a free return label as well.

**Comment by wessel-novacustom** [comment]
@Ferenc- Could you please close this issue, as can [provide a solution with a fan replacement under warranty](https://github.com/Dasharo/dasharo-issues/issues/532#issuecomment-1790220253) and because of the [improvements in the fan policy](https://docs.dasharo.com/unified/novacustom/fan-profiles/)?

**Comment by Ferenc-** [comment]
My unit has been serviced, and this issue is not reproducible since. Closing.
