### ISSUE TITLE
Power state after power fail - powered off option not working

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#557]
### Device

MSI - z790

### Dasharo version

0.9.1

### Brief summary

Upon restoring power after a failure, the machine will power on regardless of whether we had set the `Power State After Power Fail` option to `Powered Off`.

### How reproducible

100%

### How to reproduce

Enter Dasharo System Features and set the `Power State After Power Fail` option to `Powered Off`.
Save changes and reset, enter setup menu again to ensure changes have been saved.
Simulate a power failure to the DUT.
Observe that the machine powers on, though it shouldn't.

### Expected behavior

The machine should not power on after power restoration if the option is set to `Powered Off`

### Actual behavior

It does power on.

### Additional context

https://cloud.3mdeb.com/index.php/s/zjarA5MBHZfQTe9/download/log.html - test log

**Comment by SergiiDmytruk** [comment]
> Simulate a power failure to the DUT.

So, you just change the setting and power off the platform immediately, right?  If so, the behaviour is expected.  UI option enables application of the setting in `coreboot` which must update appropriate variable in CMOS.  If `coreboot` hasn't had a chance to run after the setting has been changed, the behaviour will be the same on the next run.

**Comment by filipleple** [comment]
@SergiiDmytruk unfortunately, the test saves changes and resets beforehand. The power failure is simulated after the setup menu has come up again after the reset to ensure that the option got saved. I forgot to clarify that in the issue, but the test log demonstrates it.

**Comment by macpijan** [comment]
@filipleple Please link to the specific line in test when discussing this, that would help to avoid confusion.

**Comment by macpijan** [comment]
I think it was both. Manual recheck after automated test failure has been discovered.

**Comment by SergiiDmytruk** [comment]
> Do you have any reference to such bugs @SergiiDmytruk ? Can you elaborate more?

Updating EFI variables from coreboot in order to implement automatic recovery if XMP profile resulted in unbootable system broke variable storage in some way (EDK refused to update it).  There might of course be a different reason, I just didn't find any code changes that could explain the issue, but maybe it's not here (I'm yet to check that value in EFI Shell and what coreboot thinks it is).

Rebase has changed coreboot's option storage from CMOS to SMMSTORE (where EFI variables are), is that a compatible change for Dasharo?  Sounds like data from CMOS won't be migrated, but I don't know if anything useful is stored there.

**Comment by macpijan** [comment]
I am pretty sure we have already used SMMSTORE, but will leave this for @mkopec to confirm

**Comment by SergiiDmytruk** [comment]
> I am pretty sure we have already used SMMSTORE

Well, `src/drivers/efi/option.c` file didn't exist before the rebase.  I'm talking about `get_uint_option()` and `set_uint_option()` functions.

**Comment by macpijan** [comment]
@mkopec Do you have some insight here?

**Comment by mkopec** [comment]
We previously jad the EFI variable driver enabled, but the rebase introduced another option, a backend for coreboot options that uses EFI vars instead of CMOS. So whatever code used CMOS previously, is now using the EFI var store as well.

The dasharo options were never integrated with coreboot options so we didn't have this issue before rebase.

@macpijan

**Comment by SergiiDmytruk** [comment]
> It seems that `CONFIG_USE_UEFI_VARIABLE_STORE` gets set which switches `get_uint_option()` to implementation backed by EFI variables. Given that updating EFI variables from coreboot apparently has some bugs, this might be the reason behind the issue.

There is definitely a bug somehow related to the backend.  Switching to "none" backend for options makes the setting work correctly, but with EFI backend `get_uint_option()` returns `0` every time (I thought it would return something else) and yet the board powers on automatically.

**Comment by macpijan** [comment]
According to @miczyg1 , EFI store for options should not be enabled, and this may be causing this issue

**Comment by SergiiDmytruk** [comment]
Variables aren't to blame, it's something else:
 * building with `DRIVERS_EFI_VARIABLE_STORE=n` exposes similar behaviour, so it's not UEFI variables
 * behaviour is the same on `dasharo` and `msi_ms7d25/develop` branches, so it's not rebase
 * it doesn't happen every time, it can happen multiple times in a row, then stop, then start happening again for no specific reason

Power-on state is controlled by both `nct6687d` and `pmc`, but they seem to always agree and configure everything to stay powered off.  It seems like the code is just wrong or something else is affecting it.

**Comment by SergiiDmytruk** [comment]
The issue happens on Z690-A DDR4 as well.

> [...] or something else is affecting it.

There was some weirdness with this feature right away which I attributed to lack of reboots on my part.  Looks like the missing bit of information is that platform needs to be off for more than 10 seconds, otherwise it boots when power is back on.  I tried this out manually  and then also set 9 seconds delay in tests which caused them to fail while they pass with 15 seconds delay.  10 seconds doesn't produce stable results.

I realize this sounds weird, so I flashed MSI BIOS, checked that it says "remain powered off" and simulated power failure.  Result is the same: the system boots if power returns quickly.  Maybe PSU just keeps it running for around 10 seconds.
