### ISSUE TITLE
PC Engines Dasharo v0.9.0  - firmware

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#575]
**Dasharo version (if applicable)**

**Dasharo variant (if applicable)**

**Affected component(s) or functionality (if applicable)**

**Brief summary**

The roadmap says 4.19, but we should rather port PC Engines board into dasharo branch https://github.com/Dasharo/coreboot/ which is based on the 4.21 currently.

What may be an additional challenge here, is that we have some Intel-specific code in the edk2 payload, which may need to  be generalized, or AMD part must be implemented as well. This was mentioned by @krystian-hebel . We can discuss it further in this issue.

Expected checklist:

- [x] Prepare miniconfig file
  - [x] Set coreboot's CONFIG_LOCALVERSION to v0.9.0 in miniconfig file
  - [x] Freeze the EDKII repository revision in miniconfig file
  - [x] Freeze the iPXE repository revision in miniconfig file
- [x] Prepare automated build script in bash
- [ ] Assess the feature scope of coreboot and Dasharo UEFIPayload
- [x] Add board to Github Actions CI
- [x] Fix build issues

**Additional context**

**Comment by pietrushnic** [comment]
The key question is if we can do things as they are now. I've been using a UEFI-based solution for my firewall probably for more than two years, it works without any problems. Over time, we should align features across all supported platforms, but for now, I would like to get the same quality that I already have. I doubt we have resources for development.

**Comment by macpijan** [comment]
I am not sure what the exact problem was. Best we just try with current revision and see what happens.

**Comment by SergiiDmytruk** [comment]
Looking at https://github.com/pcengines/coreboot/commits/develop/, all code changes are in upstream?  In other words:
 * there is nothing to rebase apart from configs
 * UEFI payload should be compiled and started by coreboot (might require updating fork of EDK2)
 * applicable configuration options in EFI variables need to be properly handled by the code related to PC Engines

Anything else?

**Comment by SergiiDmytruk** [comment]
OK, there are 1272 commits unique to that branch not counting merges (lots are about changelog).  Since we're likely interested in rebasing stuff in the future, merging won't work well.  Cherry-picking won't work well either due to code changes throughout the years.  So I'm assuming recommitting changes is what we're after here.  Might need to look at those 1272 commits to understand some changes.  Either way, that's for later after things start to work.

UEFI headers used by `options.c` for EFI-variables in coreboot are in Intel-specific vendor directory.  Enabled that anyway to compile.

On APU2 EDK had segmentation fault due to missing `FACS` ACPI table (the code checked only extended 64-bit field when 32-bit one was populated by coreboot).  Fixing that led to an error in `DxeMain.c` due to missing arch protocols:
```
Variable Arch Protocol not present!!

Variable Write Arch Protocol not present!!

Capsule Arch Protocol not present!!

Monotonic Counter Arch Protocol not present!!

Real Time Clock Arch Protocol not present!!
```

**Comment by krystian-hebel** [comment]
> Looking at https://github.com/pcengines/coreboot/commits/develop/, all code changes are in upstream?

That project had a peculiar release process when it comes to merging upstream changes, so local changes are buried deep in the history, but I assume you've noticed this already, based on next comment.

> there are 1272 commits unique to that branch not counting merges

A lot of those changes were made to align existing local changes to new upstream code, or fix an issue with previous implementation. Unfortunately, I'm afraid the information on background behind some changes may be found only in the release changelogs, and not in the commits themselves. I don't think there would be more than a hundred or so of meaningful changes in the end, but picking that from 1272 commits is a lot of work. It is also possible that there were conflicts during merging upstream master to that branch that were resolved during merge, so those commits may also not be 100% identical with upstream, which in turn caused more work after each next merge.

Also, some of the changes were recently submitted (or the review is ongoing) to the upstream, e.g. https://review.coreboot.org/c/coreboot/+/79852, https://review.coreboot.org/c/coreboot/+/79612, https://review.coreboot.org/c/coreboot/+/79674, to name the few. The one with ECC scrubber probably needs checking from our side to either confirm or deny `DramEccEn` being 0, I think it may have something to do with binary-patched AGESA we were using.

**Comment by SergiiDmytruk** [comment]
> Unfortunately, I'm afraid the information on background behind some changes may be found only in the release changelogs, and not in the commits themselves.

The changelog commit goes soon after the change, so it's not a big deal on its own.

> It is also possible that there were conflicts during merging upstream master to that branch that were resolved during merge, so those commits may also not be 100% identical with upstream, which in turn caused more work after each next merge.

I don't think I've seen merges with code changes, so maybe there weren't any.

> Also, some of the changes were recently submitted (or the review is ongoing) to the upstream

I guess that's not relevant to rebase onto `dasharo` which doesn't have those new commits, but will be when `dasharo` is rebased.

***

At least variable protocols are missing because nothing enables SMMSTORE.  In fact https://review.coreboot.org/c/coreboot/+/59810 disabled it.  Effectively reverting that wasn't enough to get SMMSTORE as `HAVE_SMI_HANDLER` is also required and it caused various build issue.  After finally making it compile, EDK2 side still doesn't work because there is no SMI handler, coreboot doesn't enable it .  Should it work in the end or it can't work for some reason on this platform?  Doing
```diff
-mp_init_with_smm(cpu_bus, &amd_mp_ops_no_smm);
+mp_init_with_smm(cpu_bus, &amd_mp_ops_with_smm);
```
Only led to more build dependencies and stronger impression that it won't work here.  So should it work and are there any alternatives if the answer is no?

I pushed [this WIP branch](https://github.com/Dasharo/coreboot/commits/pc-engines/) in case that's helpful (it's a merge with changes on top of it).

**Comment by SergiiDmytruk** [comment]
PR: https://github.com/Dasharo/coreboot/pull/468

**Comment by BeataZdunczyk** [comment]
Great job @SergiiDmytruk ! The PR have been merged. I'm closing this issue. We can begin preparing for the release.

**Comment by miczyg1** [comment]
not yet: https://github.com/Dasharo/coreboot/pull/467
