### ISSUE TITLE
No WiFi networks detected on MSI Z690-A WiFi DDR4 ADL

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#651]
### Device

MSI Z690-A WiFi DDR4 ADL

### Dasharo version

v1.1.3

### Affected component(s) or functionality

WiFi scanning 

### Brief summary

On Ubuntu, WiFi rescan and list (`nmcli device wifi list`) doesn't detect any networks, though on Windows it does.

### How reproducible

100%

### How to reproduce

Try to scan for WiFi networks on Ubuntu

### Expected behavior

All networks in proximity detected

### Actual behavior

No networks detected, though scanning on Windows on the same platform does detect some

**Comment by zirblazer** [comment]
Which Ubuntu version? Are you sure than it actually supports the Intel AX201 WiFi module out of the box?
https://askubuntu.com/questions/1352653/intel-ax201-wi-fi-6-is-not-working-on-ubuntu-21-04
https://askubuntu.com/questions/1377110/intel-ax201-wi-fi-6-and-ethernet-wont-work-ubuntu-20-04-and-21-10
https://askubuntu.com/questions/1495421/trying-to-get-the-ax201-wifi-card-working
Cause it seems you need some further stuff to get it working. If that's the case, then it is not Firmware related, it is OS side issue.

**Comment by BeataZdunczyk** [comment]
@filipleple, could you please verify if we tested with the AX201 WiFi module, and update the issue? It'd be great if you could add the information here: [Hardware configuration matrix](https://docs.dasharo.com/variants/msi_z690/hardware-matrix/#msi-pro-z690-a-wifi-ddr4-sn-07d2511_la1e012608)

**Comment by miczyg1** [comment]
Unfortunately no Ubuntu left on MSI Z690-A WiFi DDR4 ADL so I can't verify this particular device. To check Linux overall I have tested the Qubes OS, which was there. And WiFi is not detected there too. But the problem is that the Qubes OS was installed in vanilla mode (with current kernel 5.15). If it was installed with kernel latest as suggested here: https://www.qubes-os.org/news/2023/03/15/dasharo-fidelisguard-z690-first-qubes-certified-desktop/#special-note-regarding-the-need-for-kernel-latest

The drivers would probe the WiFi properly. Instead one can see errors in sys-net dmesg.

Z790-P detects WiFi networks on Ubuntu, the MSI Z690-A WiFi DDR4 with RPL CPU also detects the WiFi network. I suspect something was not done correctly during testing.

**Comment by renehoj** [comment]
On Qubes OS v4.1.2 you manually need to download the Linux firmware package and install it in sys-net, I think you might also need to do it on v4.2.0 if you are using Debian as the guest OS.

**Comment by miczyg1** [comment]
> On Qubes OS v4.1.2 you manually need to download the Linux firmware package and install it in sys-net, I think you might also need to do it on v4.2.0 if you are using Debian as the guest OS.

Probably. But if Qubes R4.1.2  is installed using kernel latest, the firmware should be paired with the kernel as well IIRC.

**Comment by filipleple** [comment]
On fresh installs of Ubuntu and Qubes kernel-latest the issue no longer occurs.
