### ISSUE TITLE
What is the advantage of verifying SHA256 hash signatures with GPG?

### ISSUE THREAD

**Issue by jeltsch** [Dasharo/dasharo-issues#653]
**Dasharo version**

Any

**Dasharo variant**

Any

**Question text**

To assure the integrity of a downloaded firmware file, one can check that its SHA256 hash matches the one published alongside that file. However, how to be sure that the obtained SHA256 hash hasn’t been tampered with? For this, one can check the signature published alongside the hash. That said, isn’t the integrity of the SHA256 hash and actually already of the firmware file essentially assured by the fact that they are obtained via a TLS-secured HTTP connection (`https`)? What is the advantage of checking hashes and verifying their signatures?

**Comment by pietrushnic** [comment]
@jeltsch, thanks for the question.

Our practices are heavily influenced by [Qubes OS](https://www.qubes-os.org/security/verifying-signatures/), which we consider a state-of-the-art open-source project focusing on security and privacy and saying so you can find similarities in our approach. We tried to explain the details [here](https://docs.dasharo.com/guides/signature-verification/)

Access to GPG signing keys is in 3mdeb way more limited (depending on the build, 2-3 people) than access to deployment mechanisms related to placing things in FTP, HTTP, or Github. Also, only one person can generate new keys, and that's me since I'm holding both the 3mdeb Dasharo Master Key and the 3mdeb Master Key.

So, the advantage is another layer of protection against issues related to potential attacks on our infrastructure. Qubes OS Team explains that in:
- [Should I trust this website?](https://www.qubes-os.org/faq/#should-i-trust-this-website)
- [What does it mean to “distrust the infrastructure”?](https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure)

We share their point of view, but we have a lot of things to improve to achieve their level of resiliency.

**Comment by jeltsch** [comment]
Thanks a lot for this answer. This makes perfect sense to me. So, for me as a user, whether or not I should check the SHA256 hashes depends on whether I trust that the 3mdeb infrastructure is not compromised and the TLS chain of trust works as intended.

**Comment by pietrushnic** [comment]
> Thanks a lot for this answer. This makes perfect sense to me. So, for me as a user, whether or not I should check the SHA256 hashes depends on whether I trust that the 3mdeb infrastructure is not compromised and the TLS chain of trust works as intended.

Precisely.
