### ISSUE TITLE
MSI Z790-p DDR5 XMP 3.0 profile not used + cpu AIO liquid cooling fan speed high at idle + CPU turbo boost not maintaining high clock

### ISSUE THREAD

**Issue by mlario** [Dasharo/dasharo-issues#659]
### Device

MSI Z790-p DDR5 Wifi + 96 Gb DDR 5 Corsair Vengeance CMK96GX5M2B6000C30 + Intel 14900K + AIO Arctic Freezer II 420 mm liquid cooling

### Dasharo version

v0.9.0

### Affected component(s) or functionality

DDR5 XMP profile is not used by Dasharo v0.9.0. Meaning overpriced memory sticks are not used to their full potential. Corsair Vengeance CMK96GX5M2B6000C30 has XMP 3.0 timings profile 3000 MHz and timings 30-36-36-76 while dasharo selects 2194 MHz and timings 40-37-37-70

Then CPU AIO liquid cooling fan speed at idle is high producing much noise (cpu temperature is 26C at idle). With MSI firmware it was very silent at idle

Finally, CPU turbo boost does not sustain high frequency (5.6-6 GHz). It only keeps 5.3 GHz for few seconds (CPU temp 75-80C) and then drops to 4.3 GHz (CPU temp 55C) . While with MSI firmware turbo boost clocks 5.6-6 GHz are sustained for a long time (minutes and more). Cooling capacity allows for such high frequency

### Brief summary

XMP 3.0 not used + cpu fan at high speed during idle + turbo boost not maintained

### How to reproduce

Running dasharo v0.9.0 on MSI Z790-p DDR5 WIFI

### Expected behavior

Similar to MSI firmware:

XMP 3.0 is used for DDR5
CPU AIO fan has low speed at idle if CPU temperature is low (with AIO liquid cooling)
Turbo boost sustainable for long time

### Actual behavior

RAM runs at lower speed and worse timings
CPU AIO fan spins at high speed during idle
Turbo boost is not maintained longer than few seconds

**Comment by zirblazer** [comment]
> Finally, CPU turbo boost does not sustain high frequency (5.6-6 GHz). It only keeps 5.3 GHz for few seconds (CPU temp 75-80C) and then drops to 4.3 GHz (CPU temp 55C) . While with MSI firmware turbo boost clocks 5.6-6 GHz are sustained for a long time (minutes and more). Cooling capacity allows for such high frequency
This one is almost a "working as intended". Dasharo uses Intel defaults for power limits, which for a 14900K is PL1 = 125W / PL2 = 253W / Tau = 56s / ICCMAX = 307A / AC_LL and DC_LL = 1.1 mOhms (Note that 14900K also has an alternative Extreme Config profile with 253W / 253W / 400A, but there isn't support for multiple defaults per Processor). MSI by default should run unlimited. This is pretty much documented here: https://docs.dasharo.com/guides/dasharo-reviewers-guide/#find-your-processor-intel-default-parameters
Yes, 125W PL1 for a 14900K should limit it greatly. Currently, you can NOT change the hardcoded defaults from within Firmware, albeit if you use Windows you should be able to increase PL1, PL2 and ICCMAX using Intel XTU. There was at least a single Linux tool that allowed to change PL1 and PL2, but don't recall its name. AC_LL and DC_LL can't be manually tuned from Software (It could be useful if you get the AC_LL / DC_LL values from MSI BIOS to know what defaults it uses for 14900K). I have been lobbying to add manual tuning for these values given how much they hard cap the Processors.


> DDR5 XMP profile is not used by Dasharo v0.9.0. Meaning overpriced memory sticks are not used to their full potential. Corsair Vengeance CMK96GX5M2B6000C30 has XMP 3.0 timings profile 3000 MHz and timings 30-36-36-76 while dasharo selects 2194 MHz and timings 40-37-37-70

0.9.1 has preliminary XMP implemented. It should allow you to choose between either JEDEC or one of the 3 XMP profiles, albeit I had issues with the DDR4 version because DRAM Voltage was getting ignored thus it was not stable at rated frequency and there is no way to manually tune it, not sure if it works fine for DDR5. 0.9.1 should have been released two weeks ago or so, but is still in validation. You should be able to get a precompiled RC.

 
> Then CPU AIO liquid cooling fan speed at idle is high producing much noise (cpu temperature is 26C at idle). With MSI firmware it was very silent at idle

No idea about this one. One of the developers has recently got an AIO unit and spend quite a bit of time dealing with Fan curves. But again, there is no manual control with hurts it.

**Comment by mlario** [comment]
thanks for response. would be great to be able to set cpu profiles either manualy or to use unlimited high performance profile by default.

Lets see if XMP and AIO fan curve gets fixed in next release(s)

**Comment by mlario** [comment]
> > Finally, CPU turbo boost does not sustain high frequency (5.6-6 GHz). It only keeps 5.3 GHz for few seconds (CPU temp 75-80C) and then drops to 4.3 GHz (CPU temp 55C) . While with MSI firmware turbo boost clocks 5.6-6 GHz are sustained for a long time (minutes and more). Cooling capacity allows for such high frequency
> 
> This one is almost a "working as intended". Dasharo uses Intel defaults for power limits, which for a 14900K is PL1 = 125W / PL2 = 253W / Tau = 56s / ICCMAX = 307A / AC_LL and DC_LL = 1.1 mOhms (Note that 14900K also has an alternative Extreme Config profile with 253W / 253W / 400A, but there isn't support for multiple defaults per Processor). MSI by default should run unlimited. This is pretty much documented here: https://docs.dasharo.com/guides/dasharo-reviewers-guide/#find-your-processor-intel-default-parameters Yes, 125W PL1 for a 14900K should limit it greatly. Currently, you can NOT change the hardcoded defaults from within Firmware, albeit if you use Windows you should be able to increase PL1, PL2 and ICCMAX using Intel XTU. There was at least a single Linux tool that allowed to change PL1 and PL2, but don't recall its name. AC_LL and DC_LL can't be manually tuned from Software (It could be useful if you get the AC_LL / DC_LL values from MSI BIOS to know what defaults it uses for 14900K). I have been lobbying to add manual tuning for these values given how much they hard cap the Processors.
> 
> > DDR5 XMP profile is not used by Dasharo v0.9.0. Meaning overpriced memory sticks are not used to their full potential. Corsair Vengeance CMK96GX5M2B6000C30 has XMP 3.0 timings profile 3000 MHz and timings 30-36-36-76 while dasharo selects 2194 MHz and timings 40-37-37-70
> 
> 0.9.1 has preliminary XMP implemented. It should allow you to choose between either JEDEC or one of the 3 XMP profiles, albeit I had issues with the DDR4 version because DRAM Voltage was getting ignored thus it was not stable at rated frequency and there is no way to manually tune it, not sure if it works fine for DDR5. 0.9.1 should have been released two weeks ago or so, but is still in validation. You should be able to get a precompiled RC.
> 
> > Then CPU AIO liquid cooling fan speed at idle is high producing much noise (cpu temperature is 26C at idle). With MSI firmware it was very silent at idle
> 
> No idea about this one. One of the developers has recently got an AIO unit and spend quite a bit of time dealing with Fan curves, not sure if changes are in for 0.9.1. But again, there is no manual control which hurts it if you don't like defaults.

OK, got my hands on 0.9.1 and idle fan spin is lower with less noise - that is nice improvement

New release has option for selecting XMP profiles - but same as you mentioned those cause crash also on DDR5 - system is not booting at all, and that is pity

**Comment by zirblazer** [comment]
> New release has option for selecting XMP profiles - but same as you mentioned those cause crash also on DDR5 - system is not booting at all, and that is pity
I suppose that you could recover via FlashBIOS, right?
Are you using Windows? It would be useful if you get info from the XMP profiles with a tool like Thaiphoon Burner: https://www.softnology.biz/files.html
...since Corsair doesn't really say much about them beyond standard JEDEC and highest XMP profile, so you don't know if you can get working any of the intermediate ones: https://www.corsair.com/es/es/p/memory/cmk96gx5m2b6000c30/vengeance-96gb-2x48gb-ddr5-dram-6000mt-s-cl30-memory-kit-black-cmk96gx5m2b6000c30#tab-techspecs

For comparison, Kingston modules usually have better detailed datasheets so you have all the intermediate XMP profiles, which is why I'm prefering them as you know exactly what you're getting: https://www.kingston.com/datasheets/KF560C40BBK2-64.pdf

Note that on my experience with DDR4, training time when using XMP went from around 1 minute to about 4 or 5 with 64 GiB RAM. DDR5 takes TWICE the amount of time, and you're with 96 GiB. If you want to read: https://github.com/Dasharo/dasharo-issues/issues/605

**Comment by mlario** [comment]
Hey. Yes, I did FlashBios to recover, was lazy to remove graphics card and cmos battery (I only guess but bios reset should also help with wrong XMP profile)

I use both windows and linux. Thaiphoon burner gave some errors and did not show XMP profile. RAMMon is better, I have only 1 XMP 3.0 profile - here is report. My ram requires elevated voltages (VDDQ 1.4V) for XMP to work.
[RAMMon - Memory Info.txt](https://github.com/Dasharo/dasharo-issues/files/13823066/RAMMon.-.Memory.Info.txt)

Dasharo v0.9.1 settings contain JEDEC and 3 XMP profiles. While I have only 1 profile on RAM. Anyhow I tried all 3 XMPs and left PC >1 hour on to retrain RAM. Anyhow neither XMP profile worked - PC is on but no video output or whatsoever. I rechecked it twice

So no, new Dasharo v0.9.1 does not provide stable XMP, unfortunately, at least for me

**Comment by Calandracas606** [comment]
I'm experiencing pretty much the exact same thing with my MSI Z790-p DDR5 Wifi + i9 14900k

Using MSI firmware, the CPU will boost to 5.7GHz until it reaches 100c, which is quite a long time with a 420mm AIO

With Dasharo, running stress-ng --cpu 16 will bost to 5.7 for the expected 56 seconds on PL2 until its returned to PL1 where it will throttle down to 4.8. Temperatures hovering around 60c

Using stress-ng --cpu 32 to stress all cores won't boost to 5.7GHz for more than a couple of seconds. presumably the power limits are too low to sustain all cores running at max.

Building from source and manually changing PL1=2048, PL2=2048, PL4=2999 and ICCMAX to 512 didn't make any difference. I verified that the settings are being applied with cbmem, but maybe I still did something wrong.

For reference, the outrageous values on the MSI water-cooling preset are:
- PL1 = 4096
- PL2 = 4096
- ICCMAX = 512
- AC_LL = 0.5
- DC_LL = 1.1

Its worth noting that these MSI values do not appear to be stable, the computer crashes after a few hours of stress testing, which does not occur with Dasharo.

I can't boot any XMP profiles with MSI, training fails within 30 seconds with 4x48GB, but I wasn't expecting to be able to use XMP.

**Comment by akoutian** [comment]
+1 for supporting power/current limit settings. I have recently installed Dasharo on my 14900KF desktop and would love to be able to unlock the full potential of this chip. Happy to help if needed.

**Comment by macpijan** [comment]
Request for PL moved here: https://github.com/Dasharo/dasharo-issues/issues/154
