### ISSUE TITLE
Keyboard backlight api available to operating system

### ISSUE THREAD

**Issue by Pace17881** [Dasharo/dasharo-issues#661]
### The problem you're addressing (if any)

At the moment i cannot maintain the keyboard backlight settings via kde.
Current machine: NovaCustom NV41PZ
Current OS: Debian bookworm/trixie

### Describe the solution you'd like

There is supported the default api which is used by windowmanager like kde

### Where is the value to a user, and who might that user be?

- settings can be maintain for power cord or battery mode
- changes via keyboard are visualized via kde
- light level can be set also  from widget
- 
![image](https://github.com/Dasharo/dasharo-issues/assets/24521835/1821f7d1-055a-472d-be93-b29401f95cff)
![1](https://github.com/Dasharo/dasharo-issues/assets/24521835/92e61559-e1ab-41f2-82f2-a4cb2a711c79)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by wessel-novacustom** [comment]
This used to be possible with System76 based EC firmware, but the link has been broken due to a lot of changes in the EC firmware. This is a negative result of the break of that. On the other hand, we do no longer depend on other's firmware, which is a plus.

I will discuss with my team the possibility and feasibility to integrate a driver in the Linux kernel to bring this OS controlling functionality back again.

**Comment by macpijan** [comment]
Followup for driver is being discussed here: https://github.com/Dasharo/dasharo-issues/issues/820
