### ISSUE TITLE
[Can't confirm] Hardware failure after SecureBoot Key enroll

### ISSUE THREAD

**Issue by K-Fuchs** [Dasharo/dasharo-issues#681]
**Dasharo version**

0.9.1 (Compiled using build script)

**Dasharo variant**

MSI PRO Z790-P Dasharo

**Question text**
I was using XMP during these steps.

The problem i"m facing is, that after enrolling SecureBoot Keys on Arch Linux using the command "sbctl enroll-keys -m", the system started lagging. So i decided to reboot after that the pc started just fine. 

Rebooted again, noticed a heavy stutter in the Dasharo (EDKII) settings, keypresses only registered after 2-3 seconds. Decided to recompile and reflash dasharo afterwards. On the first boot, everything seemed to work fine. I rebooted again, but without enrolling the SecurBoot Keys this time. After the reboot, same stutter in the Dasharo settings.

After approx. 30 minutes, the PC began to freeze, even in the booted OS. After a reboot, Linux would not boot anymore and hang during hardware initialization. So i decided to flash back the MSI AMI firmware. But still the same. Funny enough, Windows would boot and stop working (black screen) after installing the Intel graphics driver.

Suspecting the RAM, after some tries i was able to boot memtest86. Ran the RAM test for an hour and no issues where found.

After some time trying to get the PC to boot, the whole PC stopped POSTing altogether. No reflash was able to revive it.
One thing i noticed is, that the PCH got hot during the black screens.

I can't confirm that there is a correlation between the key enroll and the hardware dying. But I'm too affraid to try it again with my new hardware. I was able to return all parts for exchange so i can't say for sure which component died.

I installed self compiled 0.9.1 on my new hardware again, so far everything sems to work just fine. But for now, i have not enrolled SecureBoot Keys in the UEFI.

Like in the title, i can't confirm that the issue is related to the Key enroll, but the timing of the issues seemed like it  (the enroll writes to UEFI if i remember correctly).

Hardware Old:
Intel 14900k
MSI Z790P WIFI DDR5
Corsair Dominator Platinum 6200MT

New Hardware (replaced everything):
Intel 14900k
MSI Z790P WIFI DDR5
Corsair Dominator Titanum 7200MT

**Comment by zirblazer** [comment]
Urgh, this one would be so hard to troubleshoot...
I'm more suspicious about the DDR5 modules being one of those fancy RGB ones.

For how long you had XMP working with Dasharo before it blew up?
Had you any application that managed your modules RGB? I have hear quite a bit about SPD corruption that could lead to no POST with both GSkill RGB, Corsair iCUE and OpenRGB:
https://www.overclock.net/threads/corrupted-ddr5-spd-fix-tutorial.1795935/
https://forum.corsair.com/forums/topic/184617-corsair-icue-5-corrupting-spd-data-on-ram-modules/
https://old.reddit.com/r/OpenRGB/comments/zloyp2/openrgb_killed_the_leds_of_my_new_ram/

This is the most likely scenario why it also had issues when you flashed MSI BIOS. It could be theorically possible for the profiles to be corrupted in such a way that timmings are stupidly high or anything else that could make performance slow down to a crawl.
I know that Intel FSP had an option to disable SPD writes that should prevent this if enabled, but I have no idea what Dasharo or MSI defaults to. DDR5 XMP actually supports two user profiles so it is intended to be written to, nor if you require that to be disabled to actually control the RGB.

**Comment by K-Fuchs** [comment]
I did use XMP for ~2 days.

Now that you mentioned it, I did do a firmware update of my RAM using Windows iCUE before switching back to Linux. After that the PC did work fine for about 5 hours. But i think that could be a reboot, because a reboot would read the SPD again, wouldn't it?!

Would i have known, that this expensive RAM had such detrimental bugs, i wouldn't have bought another, even more expensive set. I don't need the custom profiles or the RGB rally, i just wanted fast RAM. The looks are just a nice bonus.

However, thank you for your time and help.
I just showed the "courage" and enrolled secureboot keys on Arch Linux using sbctl again and my PC still boots.......

Now i can enjoy using Coreboot on a cutting edge machine. Will support you guys with another two years of Entry subscription for this awesome work.

Regarding the FSP SPD write lock, i will look that up and compile again with that set. I don't want another dead PC i need for studying.

**Comment by zirblazer** [comment]
I do suggest to spend some time reading about SPD corruption issues to see if they can be mitigated somehow. It seems that you're not able to control the RGB via Software if you block writes to SPD. The problem is that the RGB controls sits on the same SMBus than the SPD chips, which is pretty much a hack.
For one, since you just changed the parts but most likely used the same Linux / Windows installs, can you confirm whenever you did NOT open Corsair iCUE since you swapped parts? The concern is whenever you can get silent SPD corruption (Which apparently you can, somewhat broken profiles but with apparently functional module. These could be fixable via Software flashing of the SPD). I'm not sure if in your case it was working properly until you updated the RAM SPD.
Since you didn't mentioned your RAM part number or capacity I have no idea what you exactly have, but in Windows CPU-Z and Thaipoon Burner can check the SPD info, and the latter should even be able to dump the SPDs. Here you have an example of how a CMP32GX5M2X7200C34FEW kit looks: https://www.guru3d.com/review/corsair-dominator-titanium-first-edition-ddr5-7200mhz-2x16gb-review/page-2/
Note that some vendors program Serial Numbers which means that no two SPDs from the same module model should be the same, but others do. So it should be useful to known whenever the dump of both modules is the same. Can also be useful to check for corruption. Note that some modules out of the box report checksum errors, I have some DDR4 PNY modules that works but seems badly programmed.


Also, note that Dasharo XMP implementation seems to not be applying DRAM Voltage correctly at least on DDR4. 7200 MHz is rather high and if the 1.45V these modules expect isn't supplied, most likely it will be unstable or would not POST (But you can recover with FlashBIOS).
Try just using your system without XMP nor using the RGB tools for a few days / reboot / power cycles to confirm that it works fine before trying anything else.

**Comment by pietrushnic** [comment]
> Now i can enjoy using Coreboot on a cutting edge machine. Will support you guys with another two years of Entry subscription for this awesome work.

Thank you for your support and reporting this issue.
