### ISSUE TITLE
Windows bluescreen installing ethernet drivers on VP66x0

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#739]
### Device

VP66X0

### Dasharo version

v0.9.0

### Affected component(s) or functionality

Installing ethernet drivers

### Brief summary

When trying to install ethernet drivers on Windows, watchdog timeout bluescreen occurs every time.

### How reproducible

100%

### How to reproduce

Try to install ethernet drivers on VP66x0, either locally from an .exe file or via Device Manager > Update Driver with an active internet connection. 

### Expected behavior

The drivers should install

### Actual behavior

Bluescreen on installation init

### Additional context

USB - Ethernet adapters work out of the box.

**Comment by filipleple** [comment]
I've confirmed that the ethernet ports work seamlessly on AMI stock firmware

**Comment by miczyg1** [comment]
The drivers do not install automatically for i225/i226 controllers both on AMi and Dasharo. Installing a random i225/i226 driver may cause some problems...

Other devices that are driverless are SM Bus controller, GPIO controller, SPI controller. Not sure why but there are a lots of drivers which matches the compatible device IDs in the Windows Update Catalog, but none of them want to apply automatically.

Will try with this one https://www.intel.com/content/www/us/en/download/15084/intel-ethernet-adapter-complete-driver-pack.html (29.0.1) and see if I can reproduce.

**Comment by miczyg1** [comment]
It appears we have hit a bug with PCH PCIe power/clock gating from this comment:

https://github.com/coreboot/coreboot/blob/master/src/soc/intel/alderlake/fsp_params.c#L933

So I had to enable CLKSRCREQs, assign the clocks. In order to remain some power savings I also enabled ASPM. Now I could install the drivers for all I226 Ethernet Controllers in Windows without a BSOD.

PR: https://github.com/Dasharo/coreboot/pull/483
