### ISSUE TITLE
Multiple performance tests fail on VP2420

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#763]
### Device

VP2420

### Dasharo version

v1.2.0

### Affected component(s) or functionality

Dasharo performance tests

### Brief summary

Performance tests fail

### How to reproduce

Run the Dasharo performance test suite

### Expected behavior

The tests should pass

### Actual behavior

The tests don't pass

### Additional context

See full log file [here](https://cloud.3mdeb.com/index.php/s/Mf8ttsMjTbCAn2Q)

In detail, the tests that fail are:

* Serial boot time measure test - Booting/rebooting in some cases takes longer than expected (telnet timeout)
* CPU frequency - CPU runs below the expected frequency of 800 MHz on Ubuntu, and above the expected 1997 on Windows (with and without load)
* Platform stability - An unexpected reboot occurs on both Windows and Ubuntu

**Comment by miczyg1** [comment]
A small deviation below 800MHz is possible. I have no idea how the frequency is measured, but in ideal world there is no 100% accuracy. Also undershoots/droops happen during transitions to different states, that's just how physics work (transient response).

How 1997 can be expected? The processor base frequency is 2000MHz. The value you have read is just another small deviation. For real, we should have like a +/- 50MHz window for that. Also the turbo frequency is 2600MHz, so it can burst to that frequency as well sometimes...

**Comment by mkopec** [comment]
yeah the deviation is probably due to BCLK spread spectrum, which randomly offsets the base clock +/- a % or so

**Comment by miczyg1** [comment]
I think we have to revise how we measure the current frequency. `/proc/cpuinfo` sometimes return values around 600 Mhz and 400 MHz according to logs. I have no idea how this is measured, but it doesn't seem we can relay on that.

Also `(Get-CimInstance CIM_Processor).MaxClockSpeed` seems to return some current frequency of 1997Mhz, while max is 2600Mhz (and that's what Dasharo reports in SMBIOS type 4 in MaxSpeed field). This should be fixed in tests. The frequency being between 2000MHz and 2600MHz is a correct behavior depending on the load.

I have not found any issues with firmware operation here.

**Comment by macpijan** [comment]
@miczyg1 But how did you measure frequency in your tests? Which method do you propose we should use?

**Comment by miczyg1** [comment]
>  But how did you measure frequency in your tests?

I just looked at the log attached to the issue.

>  Which method do you propose we should use?

If I had an idea, I would write it down.

**Comment by macpijan** [comment]
Frequency ranges has been implemented her: https://github.com/Dasharo/open-source-firmware-validation/pull/266
