### ISSUE TITLE
Laptop boots when plugging in the power adapter

### ISSUE THREAD

**Issue by Tijnveldhuis** [Dasharo/dasharo-issues#766]
### Component

Dasharo firmware

### Device

NovaCustom NV4x 12th Gen

### Dasharo version

v0.9.0 Heads

### Brief summary

Laptop boots when plugging in the power adapter

### How reproducible

100% reproducible.

### How to reproduce

1. Make sure that the laptop is powered off.
2. Plug in the regular 90W power adapter.

### Expected behavior

Laptop is charging without powering on.

### Actual behavior

Laptop is charging and powering on.

 

### Screenshots

https://github.com/Dasharo/dasharo-issues/assets/165149585/cb3bd542-23ce-4a06-9afb-c54365f5ed55

### Additional context

Doesn't happen on Dasharo coreboot + UEFI
The issue happens both with opened and closed laptop lid.

### Solutions you've tried

Motherboard replacement.

**Comment by Tijnveldhuis** [comment]
When powering off in the main menu of heads it will reboot itself instead of powering off. Only when you press the power button it will power off.

**Comment by mkopec** [comment]
On coreboot + UEFI we have an option in the setup menu "Power state after power failure" which would cause this behavior, I think if you had that option set before flashing Heads and then there's a chance it would persist to Heads, since it's stored in the EC itself.

However when deploying Heads via Dasharo Tools Suite we reflash the EC which should wipe all settings stored on it, so that setting should be reset to the default of `off`. Can you share the steps you took when installing Heads?

**Comment by mkopec** [comment]
I suggest you try booting Dasharo Tools Suite from a USB stick and following [EC update](https://docs.dasharo.com/dasharo-tools-suite/documentation/#ec-update) from the docs with the latest EC firmware from [here](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v172-2024-01-03)

**Comment by Tijnveldhuis** [comment]
I am already running Dasharo EC version v1.7.2

**Comment by Tijnveldhuis** [comment]
This issue is for heads only.

**Comment by macpijan** [comment]
Included in: https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases_heads/#v091-2024-06-27
