### ISSUE TITLE
Implement PlatformFlashAccessLib leveraging coreboot SMI handler

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#800]
**Brief summary**

Create a library instance that enables flash access operations within the UEFI platform with the help of SMI handler implemented in coreboot.

**Comment by SergiiDmytruk** [comment]
The EDK branch can be found [here](https://github.com/Dasharo/edk2/compare/enable-capsule-updates...capsule-flashing).  Current state: works fine in QEMU Q35, active or soft-disabled ME results in capsules disappearing during warm reset because disabling ME requires a global reset during which RAM contents is lost.

There seems to be no way of working around that other than requiring ME to be HAP-disabled. Soft-disabled ME is not "disabled enough", so coreboot uses HMRFPO method of disabling ME which involves a global reset.  In case of HAP-disabled, ME doesn't do anything, so it's even more disabled than after HMRFPO command and that should be fine for a firmware update.

Current plan is to:
 * require ME to be HAP-disabled in order to accept a capsule which requires a reset via `UpdateCapsule()` EFI API
 * make this additional function of ME disablement clear in the UI
 * might need to do a global reset to make ME restart itself after an update

***

@mkopec:
> So we essentially have to support two possible update flows: when ME is disabled we have to flash it directly (because fwupdate is not possible), and when it’s enabled we have to use the closed driver (because flashing directly will cause issues).

I think coreboot can update ME, see [this](https://github.com/Dasharo/coreboot/blob/ff4c53da3a2534647d03dc0ab52b95aaf7e83deb/src/soc/intel/common/block/cse/cse_lite.c#L1149-L1169).  I think this won't help if layout changes, which I think is the case for Dasharo+Heads.

**Comment by mkopec** [comment]
> I think coreboot can update ME, see [this](https://github.com/Dasharo/coreboot/blob/ff4c53da3a2534647d03dc0ab52b95aaf7e83deb/src/soc/intel/common/block/cse/cse_lite.c#L1149-L1169)

I believe this is for CSE Lite SKU only, we use CSE Consumer or Corporate. The tools to build a CSE Lite image are not availabe to us, I think only Google has access to those.

**Comment by SergiiDmytruk** [comment]
Sent EDK PR: https://github.com/Dasharo/edk2/pull/154 (currently refuses to update in Q35 because there is no HAP)

https://github.com/Dasharo/coreboot/pull/509 was updated with a fix and integration of latest EDK changes.

**Comment by krystian-hebel** [comment]
I've approved and merged EDK PR. For coreboot, I still have some corner cases to test regarding allocation of capsules buffer.

**Comment by krystian-hebel** [comment]
I've tested corner cases mentioned earlier with no issues, this task is now completed.
