### ISSUE TITLE
Improve SBOM in future releases for laptops

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#962]
### The problem you're addressing (if any)

The SBOM information is limited to coreobot / edk2 revisions

### Describe the solution you'd like

For some platforms, the SBOM information we provide is more extensive
Such as:
https://docs.dasharo.com/variants/protectli_vp46xx/releases/#v120-2024-03-25

**Comment by BeataZdunczyk** [comment]
@macpijan We are already addressing this as part of https://github.com/Dasharo/dasharo-issues/issues/955

> Feature request: We provided links to all components' licenses at some point. I think that information should be included in SBOM's release notes. It has already happened a couple of times when someone asked about licenses for all components included. Maybe Opness Score should also account for that somehow.

**Comment by pietrushnic** [comment]
We should publish SBOMs in the Dasharo SBOM release section; those SBOMs should comply with the state of the art in a given project. The key question is how hard it would be to introduce that:
- [SBOM coreboot](https://doc.coreboot.org/sbom/sbom.html)
- [SBOM edk2](https://uefi.org/blog/firmware-sbom-proposal)

Maybe we should have a label for SBOM since we have more issues directly or indirectly related:
- https://github.com/Dasharo/dasharo-issues/issues/129
- https://github.com/Dasharo/dasharo-issues/issues/568
- https://github.com/Dasharo/dasharo-issues/issues/955

**Comment by krystian-hebel** [comment]
Not limited to laptops, but otherwise fits this issue: AFAICT none of the SBOMs list `edk2-platforms`, even though it is used by most of the platforms supported by Dasharo.

**Comment by mkopec** [comment]
Tried to make some improvements for the upcoming release:

![image](https://github.com/user-attachments/assets/dafeb945-066c-4d86-9c0c-592403af32e9)

**Comment by mkopec** [comment]
New release notes are now live: https://docs.dasharo.com/variants/novacustom_v540tnx/releases/#v091-2024-11-07

FSP and GOP are missing because they're not public, this needs to be fixed by publishing all blobs required for building

**Comment by mkopec** [comment]
@macpijan do you think this addressess your issue?
