### ISSUE TITLE
NVIDIA card permanently active, never suspended in V560TNE

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#999]
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc2

### Test case ID

NVI002.001

### Brief summary

NVIDIA card permanently active, never suspended in V560TNE

### How reproducible

100%

### How to reproduce

Run the [NVI002.001](https://github.com/Dasharo/open-source-firmware-validation/blob/develop/dasharo-compatibility/nvidia.robot#L49) test

### Expected behavior

It should pass

### Actual behavior

The card is never suspended. No additional GUI apps that could utilize HW acceleration are running.

```
------------------------------------------------------------------------------
NVI002.001 NVIDIA Graphics power management (Ubuntu) :: Check whet... ....
Checking if mesa-utils is installed...

Package mesa-utils is installed
.
Checking if pciutils is installed...

Package pciutils is installed
NVI002.001 NVIDIA Graphics power management (Ubuntu) :: Check whet... | FAIL |
'active' does not contain 'suspended'
------------------------------------------------------------------------------
```

**Comment by philipandag** [comment]
Issue still exists in v0.9.1-rc3

**Comment by mkopec** [comment]
is the nvidia driver loaded? Please check `lsmod | grep nvidia`

**Comment by philipandag** [comment]
@mkopec 
```text
ubuntu@3mdeb:~$ lsmod | grep -i nvidia
nvidia_uvm           5021696  0
nvidia_drm            122880  2
nvidia_modeset       1507328  2 nvidia_drm
nvidia               8781824  32 nvidia_uvm,nvidia_modeset
ecc                    45056  2 ecdh_generic,nvidia
video                  73728  3 xe,i915,nvidia_modeset
ubuntu@3mdeb:~$ 
```

**Comment by mkopec** [comment]
in an x11 session, Xorg keeps the gpu powered on. fixed by switching to GNOME Wayland session:

```
cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power
Runtime D3 status:          Enabled (fine-grained)
Video Memory:               Off

GPU Hardware Support:
 Video Memory Self Refresh: Supported
 Video Memory Off:          Supported

S0ix Power Management:
 Platform Support:          Supported
 Status:                    Disabled
 ```

**Comment by philipandag** [comment]
> in an x11 session, Xorg keeps the gpu powered on. fixed by switching to GNOME Wayland session:
Xorg was not used here. Wayland was used from the beginning. Switching to Xorg and back to Wayland does not change the output of `cat /sys/class/drm/card1/device/power/runtime_status
` which is used in the test documentation and automatic tests.

Also, running `cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power` results in `cat: '/proc/driver/nvidia/gpus/0000:01:00.0/power': No such file or directory`

**Comment by philipandag** [comment]
I think the nvidia gpu is not working at all on V560TNE with the Ubuntu 24.04, kernel 6.9 which is installed on our device. I tried installing the drivers `-open` variant in versions 535, 550 and 600 using `apt` as well as Ubuntu's `Software & Updates` app, rebooting after every install, but to no avail, because running `lsmod | grep -i nvidia` always yielded no results. I checked what gpu chromium uses by going to `chrome://gpu` and it used the iGPU despite hardware acceleration being allowed in the settings. The GPU works fine on Windows so maybe I am doing something wrong,

**Comment by philipandag** [comment]
V540TND v0.9.1-rc5  kernel 6.9 is the same as https://github.com/Dasharo/dasharo-issues/issues/999#issuecomment-2312465168, both on Wayland and Xorg session (changed using the cogwhell in the low-right corner on the login screen)

- When I first run `lsmod | grep -i nvidia` i got results similar to here https://github.com/Dasharo/dasharo-issues/issues/999#issuecomment-2298851182 but after rebooting it returns nothing
- `nvidia-smi` was also working fine and after a reboot it returns `NVIDIA_SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest driver is installed and running`
- `cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power` fails, `/proc/driver/nvidia/` does not exist

Before and after this unfortunate reboot it was true that:
- `cat /sys/class/drm/card1/device/power/runtime_status` has `active` permamently

Logs after the reboot:
[cbmem-nvidia.log](https://github.com/user-attachments/files/16962240/cbmem-nvidia.log)
[dmesg-nvidia.log](https://github.com/user-attachments/files/16962241/dmesg-nvidia.log)

`dkms status`:
```
ubuntu@3mdeb:~$ dkms status
acpi-call/1.2.2, 6.8.0-35-generic, x86_64: installed
acpi-call/1.2.2, 6.8.0-39-generic, x86_64: installed
nvidia/535.183.01: added
```

`apt-cache policy nvidia-driver-530`:
```
nvidia-driver-530:
  Installed: (none)
  Candidate: 535.183.01-0ubuntu0.24.04.1
  Version table:
     535.183.01-0ubuntu0.24.04.1 500
        500 http://pl.archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages
     535.171.04-0ubuntu2 500
        500 http://pl.archive.ubuntu.com/ubuntu noble/restricted amd64 Packages
```

Looking at the outputs I suspect it is related to updating to kernel 6.9. Maybe the command on [dasharo docs](https://docs.dasharo.com/unified/clevo/post-install/#linux) is wrong? I have been just copy/pasting it.

`sudo apt install nvidia-driver-550-open` contains:
```
(...)
Module build for kernel 6.9.0-060900-generic was skipped since the kernel headers for this kernel do not seem to be installed.
(...)
```

**Comment by mkopec** [comment]
you need to also install kernel headers if you're installing a new kernel. It's a separate package. Without it the nvidia kernel driver will not be built and it won'be available.

**Comment by philipandag** [comment]
When running the command from [docs.dasharo](https://docs.dasharo.com/unified/clevo/post-install/#linux)
```
sudo apt install ./linux-headers-6.9.0-060900_6.9.0-060900.202405122134_all.deb     ./linux-image-unsigned-6.9.0-060900-generic_6.9.0-060900.202405122134_amd64.deb     ./linux-modules-6.9.0-060900-generic_6.9.0-060900.202405122134_amd64.deb 
```
The output contains:
```
(...)
linux-headers-6.9.0-060900 is already the newest version (6.9.0-060900.202405122134).
linux-image-unsigned-6.9.0-060900-generic is already the newest version (6.9.0-060900.202405122134).
linux-modules-6.9.0-060900-generic is already the newest version (6.9.0-060900.202405122134).
(...)
```

suggesting the headers are installed.

**Comment by wessel-novacustom** [comment]
FWIW: Suspend seems to work fine with Pop!_OS, while the NVIDIA graphics card is working.

**Comment by mkopec** [comment]
Works fine out of the box on Ubuntu 24.10

**Comment by SebastianCzapla** [comment]
This still failing for me at rc6 with 6.11 kernel.
Driver version 560.35.03, newest available in Ubuntu 24.10.

/sys/class/drm/card1/device/power/runtime_status shows active within all scenarios:
Nvidia is primary GPU (nvidia-smi crashes, does not show info, nvidia-smi -r cannot reset the card)
Intel is primary GPU (nvidia driver does not load, and cannot  be modprobe'd)
Tested on xorg and wayland variants.

[nvidia.robot_log.zip](https://github.com/user-attachments/files/17282056/nvidia.robot_log.zip)

**Comment by mkopec** [comment]
Is the driver actually loaded at all @SebastianCzapla ? If nvidia-smi crashes, something is wrong with the driver

**Comment by SebastianCzapla** [comment]
![image](https://github.com/user-attachments/assets/c923e6d7-41d8-4b8e-86b2-4e5c611b0477)
[dmesg-log-nvidia.zip](https://github.com/user-attachments/files/17293177/dmesg-log-nvidia.zip)

**Comment by SebastianCzapla** [comment]
nvidia-smi crashes due to OOM on ubuntu 24.10, with 560.35.03 drivers, as well as other drivers. For some reason it calls mmap() with two ridiculous numbers, precisely 48 GiB and 4 GiB.

I found workaround to that crash, it is to block nvidia persistance socket 
```sudo chmod o-w /var/run/nvidia-persistenced/socket```.

Memory leak however, still occurs when running nvidia-smi as root.

Then, nvidia-smi shows no processes running, while card state remains active, even with desktop manage disabled, with only TTY running

**Comment by SebastianCzapla** [comment]
Tested with v0.9.1-rc7
![image](https://github.com/user-attachments/assets/25c1b984-61e2-40ad-af78-88629296ca8b)

Also failed in automated tests

**Comment by mkopec** [comment]
do you have a HDMI monitor connected or USB-C dock on one of the USB-c ports?

**Comment by SebastianCzapla** [comment]
None external monitors attached, and gnome desktop manager is disabled within systemd

**Comment by mkopec** [comment]
> Only attached device is a Echo11 dock.

To which USB-C port? Please check that you're using the Thuderbolt 4 port and not the DP Alt mode port as per https://docs.dasharo.com/variants/novacustom_v560tnx/hardware-matrix/#ports-specification

**Comment by SebastianCzapla** [comment]
Retested it once again, with `watch -n1 cat /sys/class/drm/card1/device/power/runtime_status`.

Card does suspend, but it reactivates on AC connection/disconnection, and to suspend again it might take some time. I assume this is why automatic test failed, and why my manual testing failed.

Automated test case might need a rework, to include disabling of graphics environment.
